### PR TITLE
zkasm: improve handling of register clobbering and prologue/epilogue generation

### LINKED ISSUE #42: zkasm: fix prologue generation
Right now our prologue looks like this:

```
SP + 2 => SP
RR :MSTORE(SP)
```

However this is wrong – as we will advance the `SP` by two slots, and then write the `RR` to the _third_ slot, rather than one of those that we’ve reserved just now.

Instead this should look more like

```
SP + 2 => SP
RR :MSTORE(SP - 2)
```

if that's expressible in zkASM, and if not, then

```
RR :MSTORE(SP)
SP + 2 => SP
```

etc.

### PR DESCRIPTION
**Pull request by nagisa**
Best reviewd commit-by-commit. The previous failures turned out to be due to extra `stack_size = stack_size / 8` computation in the prologue/epilogue generation. I however took an opportunity to fix up the register clobbering code in general. In particular, I took a conservative approach of specifying all registers other than A as callee-saved in order to ensure we don’t rely on accidental behaviours this enables. For A I filed https://github.com/near/wasmtime/issues/45 instead, as doing otherwise makes our tests break for the time being.

You will also notice that I fixed the computation of the stack offsets: our stack pointer goes upwards, so once we reserve some space (`SP + 1 => SP`) we must access slots *below* that reserved space, so the first slot we can write to is actually at `SP - 1 .. SP`, not `SP .. SP + 1`.

Fixes #42

### CODE REVIEW

**Review by MCJOHN974 — APPROVED** [review]

File: cranelift/codegen/src/isa/zkasm/abi.rs [hunk 1]
```diff
@@ -330,13 +337,14 @@ impl ABIMachineSpec for ZkAsmMachineDeps {
         // Compute linkage frame size.
         let setup_area_size = if flags.preserve_frame_pointers()
             || !is_leaf
+            // FIXME: we don’t currently maintain a frame pointer?
```
Comment (MCJOHN974) [inline cranelift/codegen/src/isa/zkasm/abi.rs:339]: As I know we don't. Also, as I know zkAsm don't have special register for it. ``CTX`` looks like something we want to use here, but I'm not shure.

File: cranelift/codegen/src/isa/zkasm/inst/mod.rs [hunk 2]
```diff
@@ -1046,7 +1055,7 @@ impl Inst {
                 s
             }
 
-            &MInst::Extend {
```
Comment (MCJOHN974) [inline cranelift/codegen/src/isa/zkasm/inst/mod.rs:1049]: Not very understand why we switch from ``MInst`` to ``Inst``

File: cranelift/codegen/src/isa/zkasm/abi.rs [hunk 3]
```diff
@@ -294,8 +294,15 @@ impl ABIMachineSpec for ZkAsmMachineDeps {
         if amount == 0 {
             return insts;
         }
-        insts.push(Inst::AdjustSp {
-            amount: amount as i64,
+        // FIXME: is this right/sufficient for stack growing up
```
Comment (MCJOHN974) [inline cranelift/codegen/src/isa/zkasm/abi.rs:296]: I think it is. And see ``reserve``\``release`` is much better than think every time about what positive\negative value in ``adjust`` mean

File: cranelift/codegen/src/isa/zkasm/abi.rs [hunk 4]
```diff
@@ -473,25 +468,16 @@ impl ABIMachineSpec for ZkAsmMachineDeps {
...
+        _flags: &settings::Flags,
         frame_layout: &FrameLayout,
     ) -> SmallVec<[Self::I; 16]> {
         let mut insts = SmallVec::new();
-        // Adjust the stack pointer downward for clobbers and the function fixed
+        // Adjust the stack pointer upward for clobbers and the function fixed
         // frame (spillslots and storage slots).
         let stack_size = frame_layout.fixed_frame_storage_size + frame_layout.clobber_size;
-        // Each stack slot is 64 bit and can fit a u8 value.
+        // The stack (and memory in general) in zkASM is addressed in slots, rather than bytes.
```
Comment (MCJOHN974) [inline cranelift/codegen/src/isa/zkasm/abi.rs]: Am I right that I can think here ``slot`` ~= ``machine word``

**Review by MCJOHN974 — APPROVED** [review]

File: cranelift/codegen/src/isa/zkasm/abi.rs (hunk 4 above)
Comment (nagisa) [reply cranelift/codegen/src/isa/zkasm/abi.rs]: Roughly, yeah. Between the two the differences are mostly pedantic and implied. For example “machine word” does not necessarily imply aligned accesses – “machine word” would better describe the size of the memory access and it could very well be unaligned too. “slot” does a great job of implying that the memory itself is segmented into chunks (implying that you cannot really load half a word from one slot and half a word from the next one in a single operation.)

File: cranelift/codegen/src/isa/zkasm/abi.rs (hunk 1 above)
Comment (nagisa) [reply cranelift/codegen/src/isa/zkasm/abi.rs:339]: CTX is probably better used for the WASM context (since that's what it is meant for.) Frame pointers aren’t required to exist, the FIXME was largely added here pointing out that at least some of the conditions here are not useful.

File: cranelift/codegen/src/isa/zkasm/inst/mod.rs (hunk 2 above)
Comment (nagisa) [reply cranelift/codegen/src/isa/zkasm/inst/mod.rs:1049]: It was simply aliased renaming of the original `Inst` which didn’t seem particularly useful, and it being renamed didn’t help with `grep` either.
