### PR TITLE
zkasm: 64-bit zk-processor

### LINKED ISSUE #72: Is it a time to switch to 64-bit zk-processor now?
Recently I runned all our tests with 64-bit zk processor (zkevm-proverjs/feature/64bit). All except one passes, one failed due to a bug in the prover. So, maybe it is a time to start using 64-bit prover?

From my point of view
Proc of switching to 64-bit machine now
1) we will be able to work with implementing correct overflow
2) with 64-bit zkasm we will able to implement everything end-to-end, fully, with all corner cases, instead of implementing base logic now and work with corner cases later.

Cons:
1) 64-bit prover have some bugs now. It will block working on some opcodes, but amount of unblocked work is bigger in my opinion.
2) maybe bug in prover will lead to zkasm which should fail won't fail, and it will allow bugs in our code pass the tests, but is think probability of such scenario is small enough.

I think, if I don't missing some significant cons of this switch, now is good time to do it.

### PR DESCRIPTION
**Pull request by MCJOHN974**
Fixes #72

### CODE REVIEW

File: ci/test-zk-64.sh [hunk 1]
```diff
@@ -60,22 +60,21 @@ all_passed=true
 
 for file in "$BASE_DIR/cranelift/zkasm_data/generated"/*; do
   filename=$(basename -- "$file")
-
-  # it seems like zkasmtest.js don't set exit code to zero after succes 
-  # but set 1 after fail, so after fail in _should_fail_ test all tests fail
-  exit_code=0 
+  # it seems like zkasmtest sets 1 if smth goes wrong but don't set 0
+  # if everything is OK
+  exit_code=0
```
Comment (MCJOHN974) [inline ci/test-zk-64.sh:65]: Hm, this job is green and for first commit is red which approves my assumption. But I runned this js script right after command whith exit code 1 and exit code after script was 0, so it should be because of script provides some alternative environment??? Also, I took a look at the script, and it looks like it explicitly exit 0 if everything is OK (but I'm not an expert in js)

Comment (MCJOHN974) [reply ci/test-zk-64.sh:65]: Anyway I corrupted one of ``.zkasm`` and script shows fail on it and success on all before and all after this file, so this approach looks like working solution.

**Review by nagisa — APPROVED** [review]
